version: 2

sources:
  - name: raw
    description: Raw enterprise data sources from cloud platforms
    tables:

      - name: adobe_events
        description: Adobe digital events ingested into BigQuery
        columns:
          - name: user_id
            tests: [not_null]
          - name: event_time
            tests: [not_null]
          - name: event_type
            tests: [not_null]

      - name: media_spend_daily
        description: Daily media spend from Databricks / ADLS
        columns:
          - name: spend_date
            tests: [not_null]
          - name: campaign_id
            tests: [not_null]
          - name: spend
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: "spend >= 0"

      - name: forecast_weekly
        description: Weekly forecast data from Databricks
        columns:
          - name: week_start
            tests: [not_null]
          - name: campaign_id
            tests: [not_null]
